# Rust formatting configuration for ocpp-rs

# Edition
edition = "2021"

# Line width
max_width = 100
comment_width = 80
wrap_comments = true

# Indentation
hard_tabs = false
tab_spaces = 4

# Function definitions
fn_args_layout = "Tall"
brace_style = "SameLineWhere"

# Control flow
control_brace_style = "AlwaysSameLine"
match_arm_blocks = true
match_block_trailing_comma = false

# Imports
imports_layout = "Mixed"
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"

# Trailing commas
trailing_comma = "Vertical"
trailing_semicolon = true

# Spacing
spaces_around_ranges = false
type_punctuation_density = "Wide"

# Comments and documentation
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 80

# String formatting
format_strings = false

# Macro formatting
format_macro_matchers = true
format_macro_bodies = true

# Misc
newline_style = "Unix"
remove_nested_parens = true
use_small_heuristics = "Default"
where_single_line = false

# Experimental features (requires nightly)
# unstable_features = false
# format_generated_files = false
